[package]
name = "study_rust"
version = "0.1.0"
authors = ["lkg"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.2"
